# Deploy to Render.com on push to main branch

name: CI/CD Pipeline

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build Docker image
              run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp-node:latest .
            - name: List Docker images
              run: docker ps -a
    push_docker_image:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Docker login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ secrets.GHCR_USERNAME }}
                password: ${{ secrets.GHCR_TOKEN }}
            - name: Push Docker image to GitHub Container Registry
              run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp-node:latest
    deploy:
        needs: push_docker_image
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Render.com
              uses: render-examples/render-github-actions@v1
              with:
                api_key: ${{ secrets.RENDER_API_KEY }}
                service_id: ${{ secrets.RENDER_SERVICE_ID }}
                image: ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp-node:latest
